INSERT INTO USER(USER_ID,USER_NAME,DEPARTMENT,ROLE,LAST_LOGIN) VALUES(1,'Ravi','MFG','Developer','2021-11-19');
INSERT INTO USER(USER_ID,USER_NAME,DEPARTMENT,ROLE,LAST_LOGIN) VALUES(2,'Ashok','ADM','Admin','2021-11-30');
INSERT INTO USER(USER_ID,USER_NAME,DEPARTMENT,ROLE,LAST_LOGIN) VALUES(3,'Sathish','TFM','Tester','2021-11-21');
INSERT INTO USER(USER_ID,USER_NAME,DEPARTMENT,ROLE,LAST_LOGIN) VALUES(4,'Arun','MFG','Developer','2021-11-22');
INSERT INTO USER(USER_ID,USER_NAME,DEPARTMENT,ROLE,LAST_LOGIN) VALUES(5,'Rajesh','MFG','Developer','2021-11-23');
INSERT INTO USER(USER_ID,USER_NAME,DEPARTMENT,ROLE,LAST_LOGIN) VALUES(6,'Varun','TFM','Tester','2021-11-24');